"""add processing status to outbox events

Revision ID: 4f7996f06711
Revises: efeefca87cb7
Create Date: 2026-04-24 23:28:31.347507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7996f06711'
down_revision: Union[str, Sequence[str], None] = 'efeefca87cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE outbox_event_status_enum ADD VALUE IF NOT EXISTS 'processing'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
