"""add external_id to Account model

Revision ID: b14fee0a3cb4
Revises: d2f56218a189
Create Date: 2026-04-05 17:23:50.101254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14fee0a3cb4'
down_revision: Union[str, Sequence[str], None] = 'd2f56218a189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('external_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_accounts_user_id_external_id', 'accounts', ['user_id', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_accounts_user_id_external_id', 'accounts', type_='unique')
    op.drop_column('accounts', 'external_id')
    # ### end Alembic commands ###
